### ISSUE TITLE
Ignore base classes

### ISSUE THREAD

**Issue by gabrieldelaparra** [donnytian/Npoi.Mapper#1]
Hi there!
Is there a way to ignore the base classes? I have already tried:
mapper.Ignore<Class> and mapper.Ignore<BaseClass> but it is still saving it to the excel file.

Any clues on how to overcome this?

**Comment by donnytian** [comment]
It's confirmed and one test case added into MappingTests.cs

**Comment by gabrieldelaparra** [comment]
Thanks a lot donnytian. Could you please update the nuget package/version?
