### ISSUE TITLE
Mapper.Take<T>() works wrong sometimes when cell is numeric as text maps to string property

### ISSUE THREAD

**Issue by xjfnet** [donnytian/Npoi.Mapper#10]
sorry for my broken english
column header name is: NF
cell format is text
cell value is 2017
```cs
public class Entity
{
...
public string NF { get; set; }
...
}
var set = mapper.Take<Entity>();
var isnull = set.All(x => x.NF == null);
```
isnull is true
but this works well
```cs
Mapper.Take<dynamic>()
```

**Comment by donnytian** [comment]
1) Try set[0].Value.NF property
2) Otherwise try define NF as int type. In Excel that column might be formatted as numbers.

**Comment by xjfnet** [comment]
sorry, this is my mistake
i have two xlsx, and they has some column with the same name
i read the wrong xlsx file....
please remove this issue
