### ISSUE TITLE
Multithreading error

### ISSUE THREAD

**Issue by hongwei7458** [donnytian/Npoi.Mapper#104]
get data from other server  whith parallel.ForEach, i have an error 

code:
Parallel.ForEach(list, async item =>{
  var temp= await getdata(item);
  mapper.Put<stuent>(temp, "sheet_"+item, false);
})

error：NPOI.POIXMLException

NullReferenceException: Object reference not set to an instance of an object.

**Comment by donnytian** [comment]
sounds like an NPOI exception, I am not sure if NPOI supports multi-thread writing.
