### ISSUE TITLE
Get column as "text" when mapping a column.

### ISSUE THREAD

**Issue by timh52280** [donnytian/Npoi.Mapper#105]
First thank you very much for making this great library really is very useful, I just want more than to report a bug, I want to see if there is a way to get the data from a column as "text" instead of inferring the data type with the first column, since the excel file I process I have no way to process it by hand, this because I have a column with some keys like the following:

PaymentForm
----------------
01
02
03
04
05

And when I map the excel file, in spite of placing the property where it is mapped as a "string", the library obtains the data as shown below:

PaymentFormStringProperty
-----------------------------
1
2
3
4
5

Is there any way to get the data as "text" without having to process the file by hand?

Greetings.

**Comment by timh52280** [comment]
Thank you, I will test it and get back with the results.

**Comment by timh52280** [comment]
Doesn't work if the cells for example are Numeric with format.

**Comment by timh52280** [comment]
I think it is not really a bug but a missing feature, because for example, if the cell has CellType.Numeric NPOI does not allow to get StringCellValue, I have been reading that it is recommended to use DataFormatter and IFormulaEvaluator objects to get the text value of the cells.

**Comment by donnytian** [comment]
thanks for the info, will fix it in next release.

**Comment by timh52280** [comment]
Thank you.
