### ISSUE TITLE
 mapper.Take<dynamic>().Select(r => r.Value)读取数据不完整怎么办

### ISSUE THREAD

**Issue by mynameisRHF** [donnytian/Npoi.Mapper#109]
我在读取一个本地文件时，excel里面有1万多条数据，但是通过 mapperTake<dynamic>() .Select(r => r.Value)方法只取回了前20条数据，然而当我把前20条数据删除后，再次读取则把剩余的数据全部都读取出来了，有没有办法能解决这个问题

**Comment by donnytian** [comment]
可能是excel文件的问题吧， 可能npoi没有识别到后面还有数据

**Comment by ZhouXiang0707** [comment]
我遇见了同样的问题，不过我是因为前部分数据里面错误太多导致的，Take方法有个maxErrorRows参数，默认是10，读取到一定的错误数据之后就返回导致的，我改成mapper.Take<dynamic>(0, int.MaxValue);之后就可以读取到全部数据了
