### ISSUE TITLE
Method not found: 'Void NPOI.SS.UserModel.IWorkbook.Write(System.IO.Stream)'.

### ISSUE THREAD

**Issue by aminkosh** [donnytian/Npoi.Mapper#113]
Hi,
I have the following code:
`

    using (var ms = new MemoryStream())
            {
                var mapper = new Mapper()
                {
                    HasHeader = true
                };
                mapper.Save(ms, listDtos, "Auditlogs");
             }

`

but on mapper.Save(...) i get this error : 
**Method not found: 'Void NPOI.SS.UserModel.IWorkbook.Write(System.IO.Stream)'.**

The error is appeared after i updated the "Npoi.Mapper" Version="3.5.1" to "Npoi.Mapper" Version="4.1.0"

Any help appreciated

**Comment by bobantopukov** [comment]
Hi,

I've the same issue with "Npoi.Mapper" Version="4.1.0".

Thanks

**Comment by flkeller** [comment]
If you have installed NPOI manually in version 2.6.0 you have to downgrade to 2.5.6. Afterwards it is working fine. Npoi has changed there Interfaces in the latest minor release

**Comment by black-and-tan-doge** [comment]
Downgrading NPOI to 2.5.6 fixed the issue for me.

**Comment by tonyqus** [comment]
@donnytian Can you release a new NPOI.Mapper version based on NPOI 2.6.0?

**Comment by skovalyova** [comment]
Same happens for me when using NPOI.Mapper 4.1.0

**Comment by curllion** [comment]
我也遇到这个问题啊，各种版本都试了，一直报这个错
