### ISSUE TITLE
 Npoi.Mapper - excel file mapping hanged.

### ISSUE THREAD

**Issue by darshana2000** [donnytian/Npoi.Mapper#115]
I have been working on excel file upload which consisting rows around 25k records.

1. File size is usually around 30 MB and upload failed due to mapper issue.
    _Mapper mapper = new Mapper(stream3)_ = >//hanged- no error, no exception
2. But after the excel file opened and save as , then file size   reduced to 20 and then upload success, No error in mapping.

Would like to know is there an workaround for this ?

Below image shows the code, which using to upload excel
<img width="486" alt="image" src="https://user-images.githubusercontent.com/11071074/222318858-337d5106-e062-43eb-a4a1-460e7d2e1802.png">

**Comment by donnytian** [comment]
this seems an NPOI issue when reading the file. Sorry I don't have any workaround for now.
