### ISSUE TITLE
连续读取的问题

### ISSUE THREAD

**Issue by syht2000** [donnytian/Npoi.Mapper#118]
如果连续用
var list1 = mapper.Take<class1>(1).Select(m => m.Value).ToList();
var list2 = mapper.Take<class2>(2).Select(m => m.Value).ToList();
var list3 = mapper.Take<class2>(3).Select(m => m.Value).ToList();
..
那么除了list1之外，后面的list2/list3会出现无法读取到数据，或者读取数据有丢失，如果注释掉list1所在行，则list2能正常读取，Why?难道需要我每用一次mapper.Take均需要重新实例化一次mapper?

**Comment by donnytian** [comment]
take的结果你看看是不是已经超过最大error count了，你可以把 max error count设置的大一些
