### ISSUE TITLE
如何在用Npoi.Mapper导出数据的时候，设置表格自定义样式呢？

### ISSUE THREAD

**Issue by nextuntil** [donnytian/Npoi.Mapper#121]
RT。
比如现在希望在导出的时候实现以下样式控制：
1、表头加背景色，列名居中，字体加粗；
2、数据行斑马纹背景色处理；
3、数据列的宽度自动计算自适应；

**Comment by donnytian** [comment]
请操作`mapper.Workbook` 属性来设置样式, 具体的操作属于`npoi`的范畴, mapper主要聚焦在数据操作上.

**Comment by nextuntil** [comment]
3Q，已按回复方式处理完成。
