### ISSUE TITLE
表头不固定的时候如何处理导入和导出

### ISSUE THREAD

**Issue by nextuntil** [donnytian/Npoi.Mapper#122]
如题。
导出的数据是按时间范围查询的数据列表（比如排班表），表头是相应的时间范围（即表头字段数量不固定）。
如何处理导入和导出呢。
相应的实体无法定义。

**Comment by donnytian** [comment]
导入的话可以用dynamic 类型, 导出的话必须要先有class定义,没有class定义你导出什么东西呢
