### ISSUE TITLE
Reintroduce support for .NET Framework (with at least .NET 4.7.2)

### ISSUE THREAD

**Issue by simusr2** [donnytian/Npoi.Mapper#124]
Latest version of NPOI still suports .NET Framework (4.7.2 with 2.6.2-rc1 version of NPOI).
I've done some tests with latest stable version of NPOI (currently 2.6.1) and there is only one test that fails more than your latest versione with only .NET 6 support.

Can you reintroduce support to .NET Framework 4.7.2+?

**Comment by donnytian** [comment]
closed by v6.1
