### ISSUE TITLE
Blank cells return empty string after changes in commit 684dbc9af67eecd0ffd291556709f6bf57a86665

### ISSUE THREAD

**Issue by POFerro** [donnytian/Npoi.Mapper#129]
Hi,

After commit [684dbc9af67eecd0ffd291556709f6bf57a86665](https://github.com/donnytian/Npoi.Mapper/commit/684dbc9af67eecd0ffd291556709f6bf57a86665) blank cells mapped to string properties started returning empty string instead of null

Is it possible to revert behavior to previous behavior?

Thanks and best regards
POFerro

**Comment by donnytian** [comment]
resolved by v6.2.1
