### ISSUE TITLE
怎么读取图片

### ISSUE THREAD

**Issue by zy201114** [donnytian/Npoi.Mapper#132]
目前测试是能读物文本数据图片无法提取出来

**Comment by donnytian** [comment]
`mapper.Workbook` 是个npoi对象, 通过npoi的接口读取

**Comment by zy201114** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
