### ISSUE TITLE
Can you provide custom cell style properties or methods of the first row (header)?

### ISSUE THREAD

**Issue by VAllens** [donnytian/Npoi.Mapper#15]
I want to add a `cell style` to the header.
Therefore I had first to `Put` data, `Ignore` some fields, and then get `Workbook`, and then `foreach` and set the first row of the `cell style`.

Can you provide this functionality?
I believe there are many developers with this kind of demand.
Thank you so much.

**Comment by donnytian** [comment]
Hi, the purpose of mapper is to take care data export and import, if you want to set styles (colors, fonts, borders and etc.), probably you should use NPOI APIs directly. 

Or you are asking something about format? Actually there are `Format` overloads to specify formats for properties. See if this is what you want.

**Comment by donnytian** [comment]
To set styles for header cells, you have to populate `ICellStyle` using the Workbook => `workbook.CreateCellStyle()`, so operations on NPOI APIs are inevitable.

**Comment by donnytian** [comment]
I used to create a mapper with an existing Excel file as template, in which the styles are set nicely manually. Then you can put your data and then save it as new files.

**Comment by VAllens** [comment]
I think, since your `Mapper` has exposed the `IWorkbook` interface, and not fully sealed (that is, internal processing).
So I think it's totally possible to add a `ICellStyle` property `DefaultHeaderCellStyle` in `Mapper` or add an overload method for `Save`, using `Action<ICellStyle>` as a parameter.

Thanks :)

**Comment by donnytian** [comment]
I will add below method to mapper, is that fine?
```csharp
public void ForHeader(Action<ICell> headerAction)
```
Then you can do below things:
```csharp
            mapper.ForHeader(cell =>
            {
                if (cell.ColumnIndex == 11)
                {
                    var style = cell.Sheet.Workbook.CreateCellStyle();
                    style.LeftBorderColor = 120;
                    cell.CellStyle = style;
                }
            });
```

**Comment by VAllens** [comment]
Of course, this design is more free and better. :)
