### ISSUE TITLE
Ignore Columns By Property Name (or Names)

### ISSUE THREAD

**Issue by rhoeting** [donnytian/Npoi.Mapper#18]
First off, awesome tool!  As an enhancement, would it be possible to overload the Ignore method to pass properties by property name (as a string), or list of names.  Passing in property selector is handy, but it'd be nice to pass in strings.

**Comment by donnytian** [comment]
Hi, 
Thanks for your attention!
I will add an extension like this:
`public static Mapper Ignore<T>(this Mapper mapper, params string[] propertyNames)
`
Hope this is fine.
