### ISSUE TITLE
Doesn't work with  NPOI 2.2.1

### ISSUE THREAD

**Issue by buttch** [donnytian/Npoi.Mapper#2]
Hi,
there is a message about missing method if you try to export to XLS/S with NPOI version 2.2.1 (newest) installed.
Workaround: use NPOI version 2.1.3.1.

Regards

**Comment by donnytian** [comment]
I upgraded to NPOI 2.2.1 and run unit tests, all export cases are passed. Can you paste your case or raise a PR into test cases?

**Comment by donnytian** [comment]
Closing this as I cannot reproduce the issue.
