### ISSUE TITLE
Possibility to get detected headers

### ISSUE THREAD

**Issue by DurtyFree** [donnytian/Npoi.Mapper#20]
Haven't found the possibility to get a list of all column headers.
Is there any way to get them using the NPOI Workbook maybe?

![image](https://user-images.githubusercontent.com/20757266/33214025-72ac845e-d12a-11e7-9652-518625ebf892.png)

Best regards

**Comment by donnytian** [comment]
Hi,
Try to use below method:
`public Mapper Map(Func<IColumnInfo, bool> columnFilter, Func<IColumnInfo, object, bool> tryTake = null, Func<IColumnInfo, object, bool> tryPut = null)`

`columnFilter `parameter is a function to check every column with it's header value (in IColumnInfo object).

**Comment by DurtyFree** [comment]
Thanks for the quick response so far!

But thats not what I am searching for, I am actually trying to get a list of the columns headers that the mapping engine internally keeps for mappings.

Example:  
![grafik](https://user-images.githubusercontent.com/20757266/33216597-c26cf3ac-d134-11e7-8c12-91aa3797f233.png)
I am searching for a method to get the following list of type string: "Header 1", "Second Header", "Header 3", "TestHeader"

The reason I need is this to have a list of possible columns which I can create mappings for, on runtime.

**Comment by DurtyFree** [comment]
Alright I worked out my own solution based on the available access to the excel workbook.

For anybody else here it is:
```CSharp
ISheet currentSheet = _mapper.Workbook.GetSheetAt(_mapper.Workbook.ActiveSheetIndex);
List<string> columnsHeader = currentSheet.GetRow(currentSheet.FirstRowNum).Cells.Select(columnHeader => columnHeader.StringCellValue).ToList();```

Idea @donnytian 
Would be neat to have `HeaderRowIndex` implemented to get & set the current header row index.
