### ISSUE TITLE
Invoke the Mapper.Workbook to throw exception

### ISSUE THREAD

**Issue by VAllens** [donnytian/Npoi.Mapper#21]
Please look at the code:
### The original code, but **ForHeader** method does not work. ###
``` CSharp
Mapper mapper = new Mapper();
mapper.Ignore<TModel>(t => t.Id).Put(list);

var headerCellStyle = mapper.Workbook.CreateCellStyle();
//Ignore style detail setting code...
mapper.ForHeader(cell =>
{
	cell.Sheet.AutoSizeColumn(cell.ColumnIndex);
	cell.CellStyle = headerCellStyle;
});
```

### Modified Code, it throw `NullReferenceException` at the `mapper.Workbook.CreateCellStyle()` line ###
``` CSharp
Mapper mapper = new Mapper();
mapper.Ignore<TModel>(t => t.Id);

var headerCellStyle = mapper.Workbook.CreateCellStyle();
//Ignore style detail setting code...
mapper.ForHeader(cell =>
{
	cell.Sheet.AutoSizeColumn(cell.ColumnIndex);
	cell.CellStyle = headerCellStyle;
});

mapper.Put(list);
```

### Re-modified Code ###
``` CSharp
IWorkbook workbook = new HSSFWorkbook();

Mapper mapper = new Mapper(workbook);
mapper.Ignore<TModel>(t => t.Id);

var headerCellStyle = mapper.Workbook.GetDefaultHeaderCellStyle();
//Ignore style detail setting code...
mapper.ForHeader(cell =>
{
	cell.Sheet.AutoSizeColumn(cell.ColumnIndex);
	cell.CellStyle = headerCellStyle;
});

mapper.Put(list);
```

I have to create an object for the `Workbook` property to work properly, but this is not what I want.
I looked at the code of the `Mapper` class, I think a `IWorkbook` object should be created inside the default constructor.

As follows:
``` CSharp
/// <summary>
/// Initialize a new instance of <see cref="Mapper"/> class.
/// </summary>
public Mapper()
{
	Workbook = new HSSFWorkbook();
}
```

After that, the `Workbook` attribute non-null judgment code in your other methods can be deleted.
If you agree to do this, pay attention to your **`Save`** method

**Comment by donnytian** [comment]
Hi,
`Workbook `will keep null in the default mapper constructor so that `Save `overloads can choose format (xls or xlsx) later.
This is by design.

Try use below constructor for your case:

`new Mapper(new HSSFWorkbook()); // xls`
or
`new Mapper(new XSSFWorkbook()); // xlsx
`

**Comment by VAllens** [comment]
Yes, I have considered this might be your design reason.
So I had to explicitly initialize an instance of the `IWorkbook` interface object.
It's very frustrating.

**Comment by donnytian** [comment]
Please understand we have to support both XLS and XLSX formats.
Thanks for your help!
