### ISSUE TITLE
Cannot apply TryTake if there is error when parsing Enum

### ISSUE THREAD

**Issue by VAllens** [donnytian/Npoi.Mapper#23]
Get attribute value as friendly display name if property has `DisplayName` attribute.

Or you design a custom attribute enhancement class that provides a custom friendly display name, column display order, and so on.

Or does `Npoi.Mapper` already have a similar function? Do you have a better idea?

#### Sample data model code: ####
``` CSharp
public class CatalogCareViewModel
{
	/// <summary>
	/// ISO/国际标准
	/// </summary>
	public virtual string ISO { get; set; }

	/// <summary>
	/// German/德语
	/// </summary>
	[DisplayName("German")]
	public virtual string DE { get; set; }

	/// <summary>
	/// English/英语
	/// </summary>
	[DisplayName("English")]
	public virtual string EN { get; set; }

	/// <summary>
	/// French/法语
	/// </summary>
	[DisplayName("French")]
	public virtual string FR { get; set; }

	/// <summary>
	/// Russion/俄语
	/// </summary>
	[DisplayName("Russion")]
	public virtual string RU { get; set; }

	/// <summary>
	/// Italian/意大利语
	/// </summary>
	[DisplayName("Italian")]
	public virtual string IT { get; set; }

	/// <summary>
	/// Dutch/荷兰语
	/// </summary>
	[DisplayName("Dutch")]
	public virtual string NL { get; set; }

	/// <summary>
	/// Norwegian/挪威
	/// </summary>
	[DisplayName("Norwegian")]
	public virtual string NO { get; set; }
}
```

#### Sample excel sheet table ####
| ISO    | German | English | French | Russion | Italian | Dutch  | Norwegian |
|--------|--------|---------|--------|---------|---------|--------|-----------|
| value1 | value2 | value3  | value4 | value5  | value6  | value7 | value8    |
| value1 | value2 | value3  | value4 | value5  | value6  | value7 | value8    |
| value1 | value2 | value3  | value4 | value5  | value6  | value7 | value8    |

**Comment by VAllens** [comment]
我大体看了一下，你的组件是支持双向字段名映射的，现在这个已经没问题了。

但又有另外一个问题。
我调用了你的public static Mapper Map<T>(this Mapper mapper, string columnName, Expression<Func<T, object>> propertySelector,
            Func<IColumnInfo, object, bool> tryTake = null,
            Func<IColumnInfo, object, bool> tryPut = null)方法。
想要实现导入时的枚举值自定义转换。

### 举例：###

#### 枚举代码：####
``` CSharp
public enum Category
{
	[Description("Additional Care")]
	AdditionalCare,
	[Description("Bleach")]
	Bleach,
	[Description("Dry & Wring")]
	DryWring,
	[Description("Dry Clean")]
	DryClean,
	[Description("Iron")]
	Iron,
	[Description("Wash")]
	Wash
}
```
#### Excel表格里是这样的枚举值，比如有以下三条数据 ####
| Category |
|--------|
| Additional Care |
| Bleach |
| Dry & Wring |

导入过程没有任何异常。
``` CSharp
var list = mapper.Take<TModel>().Select(t => t.Value).ToList();
```
list得到三条为null的数据。
调试过程发现，在这里发生异常：
``` CSharp
public static bool TryGetCellValue(ICell cell, Type targetType, out object value)
......
    value = Enum.Parse(targetType, cell.NumericCellValue.ToString(CultureInfo.InvariantCulture));
......
```

**Comment by donnytian** [comment]
`Take`方法返回的对象有错误信息.

枚举值目前是严格从名字来parse的, 并没有取相应的attribute, 因为
1. 相关的attribute比较多, 包括Display, DisplayName, Description等
2. 上面这些attribute的值不能保证唯一性, 取哪一个的值都可能会导致unexpected result,给查找问题增加难度.

你的例子可以用自定义TryTake 方法解决. 首页有例子.

```csharp
mapper.Map<Sample>("columnA", o => o.MyEum, (column, o)=>
{
// custom logic to take value from cell.
}, null);
```

**Comment by VAllens** [comment]
对于枚举的处理，我觉得应该增加`try catch`处理，使程序尽可能的健壮，以及延后引发异常。
![image](https://user-images.githubusercontent.com/5094922/34036732-30138280-e1c1-11e7-96dd-c4fe43a669eb.png)
这样处理，当遇到我这种情况，如果我定义了TryTake，程序将顺利执行。
如果我没有定义TryTake，程序延后到这里引发异常。
![image](https://user-images.githubusercontent.com/5094922/34036833-79e80fca-e1c1-11e7-9694-4a923eec84a7.png)

**Comment by VAllens** [comment]
Hi, Donny.
还记得之前说过的自动化发布`NuGet`包吗？完全可以在`AppVeyor`上做到。
每次`git push`触发`AppVeyor`构建并且测试通过后发布小版本（如：3.1.0.yyyy）到`NuGet`。
打`tag`发布常规版本（如：3.1.x.yyyy）到`NuGet`。
这个过程涉及到的密钥/`token`等安全信息，可以通过`环境变量`传入，以及使用`AppVeyor`自带的[Encrypt](https://ci.appveyor.com/tools/encrypt)加密，防止泄漏。

**Comment by donnytian** [comment]
非常感谢, 我会看一下!
