### ISSUE TITLE
I want to get the title can not be estimated

### ISSUE THREAD

**Issue by JHeLiu** [donnytian/Npoi.Mapper#27]
I want to get the title can not be estimated,
Although I found the value I needed on dynamic, I would like to get the title how to get it?

**Comment by donnytian** [comment]
不好意思不太明白, 用中文好吗.

**Comment by chengfeng0119** [comment]
excel字段标题，修改实体属性ColumnAttribute和DisplayAttribute，无效果

**Comment by donnytian** [comment]
unclear description, closing
