### ISSUE TITLE
TryPutCell does not seem to work when using a custom column resolver.

### ISSUE THREAD

**Issue by garyandrewturner** [donnytian/Npoi.Mapper#3]
Appears to be an issue in Mapper.cs -> Put<T>( ...

SetCell not always called if using resolver.

From this:-

                    if (column.Resolver != null)
                    {
                        column.Resolver.TryPutCell(column, out value, o);
                    }
                    else
                    {
                        SetCell(cell, value, column, setStyle: overwrite);
                    }

To this:-

                    if (column.Resolver != null)
                    {
                        column.Resolver.TryPutCell(column, out value, o);
                    }

                    SetCell(cell, value, column, setStyle: overwrite);

Regards,

Gary

**Comment by donnytian** [comment]
Gary,
Thanks for your attention. Will plan to fix this in the middle of Oct.

Thanks,
Donny

**Comment by donnytian** [comment]
And we have to respect the return value from `Resolver.TryPutCell`
