### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by lebigbigworld** [donnytian/Npoi.Mapper#36]
1. Is there any property to set to skip certain number of lines from beginning?
2. Does the column attribute mapping support chinese?

Thanks

**Comment by donnytian** [comment]
Hi,
1. This feature is to be done.
2. I don't think so as only English chars are acceptable for a property name.
Thanks!

**Comment by seabass223** [comment]
is there a way to set the formula and style of a cell? Or a way to override what cell attributes NPOIMapper will tell NPOI to create?

**Comment by donnytian** [comment]
No, the mapper is mainly for data manipulation, for formula and style, we'd better use NPOI API directly.
