### ISSUE TITLE
Mapper.Save Closes stream

### ISSUE THREAD

**Issue by groogiam** [donnytian/Npoi.Mapper#38]
Calling Mapper.Save and passing in a stream seems to close the stream. For files this is ok but if this is content we want to stream from a web server this causes errors when trying to write the data to the response. Would it be possible to create an overload which takes a "closeStream" boolean parameter? This would allow the existing stream to be seeked to zero and sent over the wire from asp.net core.

**Comment by donnytian** [comment]
Hi Greg, the closing behavior is done by NPOI itself, not sure if I can control it or not...

**Comment by minskiter** [comment]
@donnytian NPOI support the IWorkBook.Write(stream,true) that does not close the stream
``` c sharp
var stream = new MemoryStream();
book.Write(stream, true);
stream.Seek(0, SeekOrigin.Begin);
return Task.FromResult(stream);
```

**Comment by minskiter** [comment]
Solution:
``` c sharp
 var book = new NPOI.XSSF.UserModel.XSSFWorkbook();
 var map = new Mapper(book).Map... // Map some properties
map.Put(data);
stream = new MemoryStream();
(map.Workbook as NPOI.XSSF.UserModel.XSSFWorkbook).Write(stream, true);
stream.Seek(0, SeekOrigin.Begin);
```
