### ISSUE TITLE
FR: Map to Enum by Enums Description or/and Display attribute

### ISSUE THREAD

**Issue by hidegh** [donnytian/Npoi.Mapper#43]
**FEATURE REQUEST**

**Is there a support to map string to enum values, based on the defined DescriptionAttribute or DisplayAttribute (would choose probably this) on then enum values?**

Common scenario is to use abbreviations with enums as well. Also the enum's property is used inside the code (like gold/silver/bronze client) and in excel we might consider to use some abbreviations (G/S/B) which when importing from excel should be converted to the proper enum value.

**Comment by donnytian** [comment]
the solution would be to pass a custom Func when doing the mapping.
