### ISSUE TITLE
FS: support importing to Nullable<bool> from specific values (1/0, Y/N, T/F, A/N, I/N, ...)

### ISSUE THREAD

**Issue by hidegh** [donnytian/Npoi.Mapper#44]
**FEATURE REQUEST**

In some cases (localization) the Y/N value do change (A/N or T/F or I/N). 

**Is there an extended Nullable<boolean> mapping support which could handle locale string value to Nullable<bool> conversion?**

**Comment by donnytian** [comment]
hi please use `Map` overload to specify the custom logic.
