### ISSUE TITLE
 请问怎么对 target.Items 深层的嵌套？

### ISSUE THREAD

**Issue by pufeilong** [donnytian/Npoi.Mapper#46]
<pre>
<code>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Npoi.Mapper;
using Npoi.Mapper.Attributes;

namespace WS.NPOI
{
    class Program
    {
        static void Main(string[] args)
        {
            string path = @"F:\test.xlsx";
            var list = new Helper().ToMapper(path);
        }
    }
    public class Helper
    {
        public List<AClass> ToMapper(string filePath)
        {
            Mapper mapper = new Mapper(filePath);
            mapper.HeaderRowIndex = 0;
            mapper.HasHeader = true;
            var item = new BClass();
            mapper = mapper.Map(
                  col => { return true; },
                 (col, target) =>
                 {
                     // 请问怎么对 target.Items 深层的嵌套？
                     ((AClass)target).Items.Add(item);
                     return true;
                 });

            var list = mapper.Take< AClass >(0).Select(s => s.Value).ToList();
            return list;
        }
    }
    public class AClass
    {
        public AClass()
        {
            Items = new List<BClass>();
        }
        [Column("columnName1")]
        public int MyColumnName { get; set; }

        public List< BClass > Items { get; set; }
    }
    public class BClass
    {
        [Column("columnName21")]
        public string MyColumnName1 { get; set; }
        [Column("columnName22")]
        public string MyColumnName2 { get; set; }
    }
}

</code>
</pre>

**Comment by donnytian** [comment]
it is not supported yet.
