### ISSUE TITLE
导出的Excel（xlsx格式）在Microsoft Office中打不开，WPS中打开正常

### ISSUE THREAD

**Issue by wuxfly6** [donnytian/Npoi.Mapper#49]
使用Npoi IWorkbook的方式导出的excel在两者中打开都正常，使用3.3.0版本的Npoi.Mapper导出，在Microsoft Office中打开会提示如图
![image](https://user-images.githubusercontent.com/13110666/53611714-7a420f80-3c0a-11e9-8892-d506dea8c59f.png)无论点击是或者否都不能正常打开。
`           //var stream = new MemoryStream();
            //var mapper = new Mapper();
            //mapper.Format<ProducePlanExportDto>("yyyy-MM-dd", ps=> ps.DeliverPeriod)
            //    .Format<ProducePlanExportDto>("yyyy-MM-dd", ps=>ps.ApplyTime)
            //    // 将各个属性映射为中文列名
            //    .Map<ProducePlanExportDto>("序号", o=>o.SeqNO)
            //    .Map<ProducePlanExportDto>("合同编号", o=>o.ContractNO)
            //    .Map<ProducePlanExportDto>("产品编号", o=>o.ProductNO)
            //    .Map<ProducePlanExportDto>("客户", o=>o.CustomerName)
            //    .Map<ProducePlanExportDto>("营销代表", o=>o.MarketerName)
            //    .Map<ProducePlanExportDto>("交货日期", o=>o.DeliverPeriod)
            //    .Map<ProducePlanExportDto>("物料代码", o=>o.Code)
            //    .Map<ProducePlanExportDto>("产品型号", o=>o.ProductModelName)
            //    .Map<ProducePlanExportDto>("规格参数", o=>o.Spec)
            //    .Map<ProducePlanExportDto>("数量", o=>o.Qty)
            //    .Map<ProducePlanExportDto>("创建时间", o=>o.ApplyTime)
            //    .Map<ProducePlanExportDto>("备注", o=>o.Remarks)
            //    .Map<ProducePlanExportDto>("是否禁用", o=>o.Disabled);

            //// 将数据保存到stream中
            //mapper.Save(stream, objs, "生产计划评审");
            //// 获取stream的buffer
            //var buffer = stream.GetBuffer();
            //stream.Dispose();
            //return buffer;`
其中objs为List<T>的数据

**Comment by tonyqus** [comment]
@donnytian 这个issue直接关了吧, npoi的锅
