### ISSUE TITLE
mapper.Take<dynamic>同一个Excel两个Sheel，两次获取，标题都是第一个的，但内容是对的。

### ISSUE THREAD

**Issue by chinasqzl** [donnytian/Npoi.Mapper#50]
![image](https://user-images.githubusercontent.com/16968103/56414336-d6e1b280-62bc-11e9-98b4-458278b7a556.png)
![image](https://user-images.githubusercontent.com/16968103/56414360-e7922880-62bc-11e9-9883-3b7ed034ffe6.png)

![image](https://user-images.githubusercontent.com/16968103/56414495-48b9fc00-62bd-11e9-8f10-345d5ef2c14e.png)
![image](https://user-images.githubusercontent.com/16968103/56414518-5c656280-62bd-11e9-8ac6-8130b2a622e8.png)

这是Bug吗？还是我的用法不对？

**Comment by donnytian** [comment]
it's a bug. property names for 2 sheets are mixed...
seems hard to fix
