### ISSUE TITLE
Try to set HeaderRowIndex but dosen't work

### ISSUE THREAD

**Issue by a157147899** [donnytian/Npoi.Mapper#53]
Hi,

My demo excel has two headers, the first header for Chinese Name and the second one is the actual column name of the table. 

I have tried to set HeaderRowIndex to 1 or 2, but the mapping result is not expected, which the value of the properties is the default value. But if I just keep single hearer, it works fine.

Below are my code and excel:
`

                var mapper = new Mapper(fullPath);
                mapper.HeaderRowIndex = 1;
                var objs = mapper.Take<ProductDTO>().ToList();

`
![image](https://user-images.githubusercontent.com/1812136/61021559-23d5b080-a3f6-11e9-96e7-6efca15cfb8b.png)

**Comment by Rwing** [comment]
because this PR stil not merged.
https://github.com/donnytian/Npoi.Mapper/pull/51

**Comment by donnytian** [comment]
replace it with `FirstRowIndex`, see #56
