### ISSUE TITLE
Support for System.Guid .NET property type

### ISSUE THREAD

**Issue by bkwdesign** [donnytian/Npoi.Mapper#55]
I think having to create a custom mapper to parse System.Guid values from a spreadsheet is something the mapper should have built in

If this is not going to be supported, can an example be added to the README .. as I had a hard time making a custom mapper for doing this

.NET sample object:

```Csharp
    public class MySampleTupleObject
    {
        public string Id { get; set; }

        public System.Guid ProcessId { get; set; }
    }
```

**Comment by donnytian** [comment]
fixed in v3.5
