### ISSUE TITLE
Support for .NET Framework 4.0

### ISSUE THREAD

**Issue by tiagossa1** [donnytian/Npoi.Mapper#60]
Hi.
I installed NPOI on a project that is targeting .NET Framework 4.0, but when I tried to install NPOI.Mapper, it doesn't install, since it's targeting for >4.5.

Is there any specific reason why you don't support 4.0?
Thanks.

**Comment by donnytian** [comment]
fixed in v3.5

**Comment by tiagossa1** [comment]
thanks!
