### ISSUE TITLE
ColumnAttribute not work on put()/save() method while batch save data

### ISSUE THREAD

**Issue by zhaokuohaha** [donnytian/Npoi.Mapper#61]
Hi 我有这样一个需求: 因为数据量过大, 所以需要分批次写入文件.  结果我发现在调用 put() 方法 或者save() 方法的时候, 对于字段名和ColumnAttribute名字不一样的列, 在第1次写入之后就会因为列名不匹配导致不能正常写入, 效果如下:
> 测试代码见:  https://github.com/zhaokuohaha/SimpleTest/blob/master/SimpleTests/NpoiTest.cs
--- 
Hi I have this requirement:  because the amount of data is too large, I need to write to the file in batches.  butI found that when calling the put () method or save () method, for columns with different field names and ColumnAttribute names, After the first write, it will not be able to write normally due to the mismatch of column names, the effect is as follows:
> test code:  https://github.com/zhaokuohaha/SimpleTest/blob/master/SimpleTests/NpoiTest.cs

![image](https://user-images.githubusercontent.com/16274628/82937273-74300f80-9fc2-11ea-9f41-35db896cf49b.png)

**Comment by donnytian** [comment]
@zhaokuohaha 请问这个问题在最新版中还存在吗？
另外建议不要在循环中创建一样的对象， 可以放到循环外面
```cs
var mapper = new Mapper(path);
```

**Comment by zhaokuohaha** [comment]
试了一下可以了。  mapper放到外面的话， 在save完了之后会及时释放掉内存么？  数据量很大的话记得之前内存一致占用很高

**Comment by donnytian** [comment]
数据量大的话， 内存占用主要是User对象， 它们既然已经在内存里了， mapper里的只是对象引用。
如果循环很多最好还是放外面，少创建许多的mapper对象。
但是具体情况你可以测试一下。
