### ISSUE TITLE
ExcelMapper take<dynamic> fails on extract - v3.5

### ISSUE THREAD

**Issue by rory-a-hunt** [donnytian/Npoi.Mapper#66]
when running:
var rowInfos = excelMapper.Take<dynamic>(stepCfg.SheetConfig.Sheetname).ToList();

fails with error: System.NullReferenceException: 'Object reference not set to an instance of an object.'
error details:

Note: Sheet has nullable date cols - which are intermittently populated - Error has occurred after update to Mapper 3.5 and NPOI 2.5.1

  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Object reference not set to an instance of an object."} | System.NullReferenceException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2147467261 | int
  | HelpLink | null | string
  | IPForWatsonBuckets | 0x00007ffc0b236886 | System.UIntPtr
  | ▶ InnerException | null | System.Exception
  | IsTransient | false | bool
  | Message | "Object reference not set to an instance of an object." | string
  | RemoteStackTrace | null | string
  | Source | "NPOI" | string
  | StackTrace | "   at NPOI.SS.UserModel.DateUtil.GetJavaCalendar(Double date, Boolean use1904windowing, TimeZone timeZone, Boolean roundSeconds)" | string
  | ▶ TargetSite | {System.DateTime GetJavaCalendar(Double, Boolean, System.TimeZone, Boolean)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | WatsonBuckets | null | object
  | _HResult | -2147467261 | int
  | _className | null | string
  | ▶ _data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | _dynamicMethods | null | object
  | _exceptionMethod | null | System.Reflection.MethodBase
  | _helpURL | null | string
  | ▶ _innerException | null | System.Exception
  | _ipForWatsonBuckets | 0x00007ffc0b236886 | System.UIntPtr
  | _message | "Object reference not set to an instance of an object." | string
  | _remoteStackIndex | 0 | int
  | _remoteStackTraceString | null | string
  | _source | "NPOI" | string
  | ▶ _stackTrace | {sbyte[48]} | object {sbyte[]}
  | _stackTraceString | null | string
  | _watsonBuckets | null | object
  | _xcode | -532462766 | int
  | _xptrs | 0x0000000000000000 | System.IntPtr
  | ▶ Static members |   |  

![image](https://user-images.githubusercontent.com/8929049/87530994-fb2b6b00-c688-11ea-8806-a794a25070bb.png)

**Comment by donnytian** [comment]
Hi, can you please upload your file and paste the mapping snippet?

**Comment by rory-a-hunt** [comment]
Hi @donnytian  - I have moved on from this job now - so no longer have the files and code - but the problem only occurred when using dynamic types when the data in the top column was null. It seems like NPOI does data type mapping on the first data row - causing errors when a lower row with an incompatible data type is seen. 
I the above example - LaunchDate is ingested fine if the first row is populated and lower rows are null - but errors if data row 1 is null . . . I suspect excel cell types might also not be helping - but in either case the old "object not set" should probably be caught. Sorry to not have the code any more - but hopefully this description helps! Great library!

**Comment by donnytian** [comment]
please use the new api `TakeDynamicWithColumnType()` in the v 4.1
feel free to reopen if there is still an issue with you.
