### ISSUE TITLE
IgnoredNameChars not working with dynamic

### ISSUE THREAD

**Issue by xleon** [donnytian/Npoi.Mapper#7]
There´s a column named "N.I.F.".
I set the mapper like: 

    _mapper = new Mapper(filePath) { IgnoredNameChars = new[] { '.' } };

The column is totally ignored when:

    _mapper.Take<dynamic>()

Though it works if I change the column name to "NIF"

**Comment by donnytian** [comment]
fixed. and BTW, '.' is included in default ignored chars. you don't need specify it.

**Comment by xleon** [comment]
Cool! 
Btw, is the nugget updated as well?

**Comment by donnytian** [comment]
Will revision to 3.0.1 very soon. Thanks for your reminder!
