### ISSUE TITLE
mapper.Take<T>() adding invalid, null row to collection

### ISSUE THREAD

**Issue by boney0002** [donnytian/Npoi.Mapper#76]
I'm not sure if I'm doing something wrong, but if I am I don't see where. I am reading in an excel spreadsheet, and using mapper.Take<T>() to map to my class, then doing some validation on each row. The mapper is returning an invalid null row with a row number that does not even exist in my spreadsheet. I go from a valid row, row number 8, to invalid null, row number 11.

Screenshot:
![Row11](https://user-images.githubusercontent.com/22060305/110500731-21da5e00-80bf-11eb-94f6-ac39a34bff0f.PNG)
![Capture](https://user-images.githubusercontent.com/22060305/110500880-420a1d00-80bf-11eb-951f-5284d21b0158.PNG)

**Comment by donnytian** [comment]
please try with the latest version as we upgraded the NPOI version
