### ISSUE TITLE
Custom Try Put resolver to handle array fields

### ISSUE THREAD

**Issue by superfabulousmax** [donnytian/Npoi.Mapper#78]
Is it possible to map an array property to be such that each element of the array is its own column in the exported excel?
The name of the excel column would be the same as the column name attribute above the property. 

I would also like to know if there is a good way to interlace the array elements of separate arrays for e.g have two arrays with 2 items: arr1 and arr2. It would work such that the exported excel has arr1[0] column, then arr2[0] column, then arr1[1] and arr2[1] columns.

**Comment by donnytian** [comment]
sounds like a very customized requirement, suggest to check out the `Custom column resolver
` section in the README, you will have more control over excel value and target object.
