### ISSUE TITLE
请问支持导出合并单元格的EXCEL么？

### ISSUE THREAD

**Issue by nextuntil** [donnytian/Npoi.Mapper#79]
如题。

**Comment by donnytian** [comment]
In order to export data in a merged cell, either pass in a pre-formatted workbook(with desired merged cells) for mapper's constructor, or use NPOI API to format `mapper.Workbook` after you `Put()` the data.

**Comment by nextuntil** [comment]
> In order to export data in a merged cell, either pass in a pre-formatted workbook(with desired merged cells) for mapper's constructor, or use NPOI API to format `mapper.Workbook` after you `Put()` the data.

3Q，目前也是自己先处理好合并单元格然后再Put的。
