### ISSUE TITLE
Npoi.Mapper 能设置xlsx 单元格的宽度吗?

### ISSUE THREAD

**Issue by Listen1421** [donnytian/Npoi.Mapper#86]
Npoi.Mapper 默认导出的execl内容 单元格都是默认宽度，导致时间显示是##### ,长内容 单元格 内容超出单元格，Npoi.Mapper 能设置xlsx 单元格的宽度吗?

**Comment by donnytian** [comment]
没有直结支持， 可以在`Put`之后用npoi的api操作`mapper.Workbook`
