### ISSUE TITLE
Would it to upgrade the version of NPOI to the latest

### ISSUE THREAD

**Issue by hamgeorge** [donnytian/Npoi.Mapper#93]
Hi,

NPOI has released 3 versions which are higher than the version in this project.
To keep the version of NPOI and Npoi.mapper same, could we upgrade the version of NPOI  to latest?

Thanks,
George

**Comment by juho2-hamk** [comment]
Yes please. I've been unable to update NPOI and SharpZipLib because Npoi.Mapper depends on outdated NPOI.

**Comment by tonyqus** [comment]
@donnytian how about releasing a new version based on NPOI 2.5.6?

**Comment by donnytian** [comment]
just released v4 with NPOI 2.5.6
