### ISSUE TITLE
请问怎么读取嵌入的图片呢？

### ISSUE THREAD

**Issue by caopengfei** [donnytian/Npoi.Mapper#96]
通过string类型读取出来的字符串为“=DISPIMG("ID_520A6F034A964DA395EC648CC8E9A4A3",1)”，该怎么才能读取到图片的数据呢？

**Comment by donnytian** [comment]
读取图片需要详细看一下NPOI的文档, 这个项目只是用来转换数据, 涉及作其他资源的操作请直接使用底层的NPOI接口.
