### ISSUE TITLE
Take<dynamic> but always take a text column

### ISSUE THREAD

**Issue by BobBonser** [donnytian/Npoi.Mapper#97]
I am having using the dynamic take with some excel files.  Specifically with files that have columns that are a mixture of alpha-numeric and all numeric columns.  It set the datatype as a double column if the first entry is numeric and then when it encounters an alpha-numeric entry it errors and sets the value to 0.

What I want to do is read the entire sheet as a text column no matter what the data is in in the Excel file.  

Is there anyway to do that??

 var mapper = new Mapper(workbook);
 var sheetRowData = mapper.Take<dynamic>(sheet.SheetName);

**Comment by donnytian** [comment]
If you can manually process the Excel file, pls open it, then format the first data cell on that column as Text.
There is no way by code so far. The code infers the data type by the cell format.

**Comment by donnytian** [comment]
fixed in next release
